version: '3'

services:

  dachs:
      container_name: dachs
      image: gavodachs/dachs:latest
      command: ['--rcfile','/start.sh']
      tty: true
      network_mode: 'bridge'
      ports:
        - 8080:8080
