version: '3'

services:
  dachs:
    image: gavodachs/dachs:latest

    build:
      context: ./dachs 
      dockerfile: Dockerfile

    container_name: dachs
    command: ['--rcfile','/start.sh']
    tty: true
    network_mode: 'bridge'
    ports:
      - 8080:8080
